[package]
name = "subtractesizer"
version = "0.1.0"
edition = "2018"

[lib]
name = "subtractesizer"
crate-type = ["cdylib"]

[dependencies]
rb = { path = "./libs/rb-0.3.2" }

[dependencies.pyo3]
version = "0.9.2"
features = ["extension-module"]
