name: Rust

on:
  push:
    branches: [ master dev ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: SetRelease
      run: rustup override set nightly
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
